
/*
 * 
 */

package fr.xebia.ws.travel.antifraud.v1_0;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2011-11-06T17:41:50.252+01:00
 * Generated source version: 2.3.3
 * 
 */


@WebServiceClient(name = "antiFraudService", 
                  wsdlLocation = "file:/Users/slm/Documents/Xebia/AtelierPerf/export/xebia-spring-travel-common/src/main/resources/META-INF/wsdl/antiFraudService-1.0.wsdl",
                  targetNamespace = "http://ws.xebia.fr/travel/antifraud/v1_0") 
public class AntiFraudService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.xebia.fr/travel/antifraud/v1_0", "antiFraudService");
    public final static QName AntiFraudServiceSOAP = new QName("http://ws.xebia.fr/travel/antifraud/v1_0", "antiFraudServiceSOAP");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/slm/Documents/Xebia/AtelierPerf/export/xebia-spring-travel-common/src/main/resources/META-INF/wsdl/antiFraudService-1.0.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/Users/slm/Documents/Xebia/AtelierPerf/export/xebia-spring-travel-common/src/main/resources/META-INF/wsdl/antiFraudService-1.0.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public AntiFraudService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AntiFraudService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AntiFraudService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns AntiFraudService
     */
    @WebEndpoint(name = "antiFraudServiceSOAP")
    public AntiFraudService getAntiFraudServiceSOAP() {
        return super.getPort(AntiFraudServiceSOAP, AntiFraudService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AntiFraudService
     */
    @WebEndpoint(name = "antiFraudServiceSOAP")
    public AntiFraudService getAntiFraudServiceSOAP(WebServiceFeature... features) {
        return super.getPort(AntiFraudServiceSOAP, AntiFraudService.class, features);
    }

}
