package fr.xebia.ws.travel.antifraud.v1_0;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.3.3
 * 2011-11-06T17:41:50.176+01:00
 * Generated source version: 2.3.3
 * 
 */
 
@WebService(targetNamespace = "http://ws.xebia.fr/travel/antifraud/v1_0", name = "antiFraudService")
@XmlSeeAlso({ObjectFactory.class})
public interface AntiFraudService {

    @WebResult(name = "out", targetNamespace = "http://ws.xebia.fr/travel/antifraud/v1_0")
    @RequestWrapper(localName = "CheckBooking", targetNamespace = "http://ws.xebia.fr/travel/antifraud/v1_0", className = "fr.xebia.ws.travel.antifraud.v1_0.CheckBooking")
    @WebMethod(operationName = "CheckBooking", action = "http://ws.xebia.fr/travel/antifraud/v1_0/CheckBooking")
    @ResponseWrapper(localName = "CheckBookingResponse", targetNamespace = "http://ws.xebia.fr/travel/antifraud/v1_0", className = "fr.xebia.ws.travel.antifraud.v1_0.CheckBookingResponse")
    public java.lang.String checkBooking(
        @WebParam(name = "booking", targetNamespace = "http://ws.xebia.fr/travel/antifraud/v1_0")
        fr.xebia.ws.travel.antifraud.v1_0.Booking booking
    ) throws SuspiciousBookingException;
}
