
package fr.xebia.ws.travel.antifraud.v1_0;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.3.3
 * 2011-11-06T17:41:50.081+01:00
 * Generated source version: 2.3.3
 * 
 */

@WebFault(name = "SuspiciousBookingFault", targetNamespace = "http://ws.xebia.fr/travel/antifraud/v1_0")
public class SuspiciousBookingException extends Exception {
    public static final long serialVersionUID = 20111106174150L;
    
    private fr.xebia.ws.travel.antifraud.v1_0.SuspiciousBookingFault suspiciousBookingFault;

    public SuspiciousBookingException() {
        super();
    }
    
    public SuspiciousBookingException(String message) {
        super(message);
    }
    
    public SuspiciousBookingException(String message, Throwable cause) {
        super(message, cause);
    }

    public SuspiciousBookingException(String message, fr.xebia.ws.travel.antifraud.v1_0.SuspiciousBookingFault suspiciousBookingFault) {
        super(message);
        this.suspiciousBookingFault = suspiciousBookingFault;
    }

    public SuspiciousBookingException(String message, fr.xebia.ws.travel.antifraud.v1_0.SuspiciousBookingFault suspiciousBookingFault, Throwable cause) {
        super(message, cause);
        this.suspiciousBookingFault = suspiciousBookingFault;
    }

    public fr.xebia.ws.travel.antifraud.v1_0.SuspiciousBookingFault getFaultInfo() {
        return this.suspiciousBookingFault;
    }
}
