alter table Booking drop constraint FK6713A039BF91BB8D
alter table Booking drop constraint FK6713A03975CC21E2
alter table Customer_Booking drop constraint FKBAF24CF8C283C22C
alter table Customer_Booking drop constraint FKBAF24CF8AFFB732F
alter table Hotel_Booking drop constraint FKC3FD448EC283C22C
alter table Hotel_Booking drop constraint FKC3FD448EBF91BB8D
drop table Booking if exists
drop table Customer if exists
drop table Customer_Booking if exists
drop table Hotel if exists
drop table Hotel_Booking if exists
drop table hibernate_sequences if exists
create CACHED table Booking (id bigint not null, beds integer not null, checkinDate date, checkoutDate date, city varchar(255), creditCardExpiryMonth varchar(255), creditCardExpiryYear integer not null, creditCardName varchar(255), creditCardNumber varchar(255), creditCardType varchar(255), line1 varchar(255), phone varchar(255), smoking bit not null, state varchar(255), zip varchar(255), hotel_id bigint, user_username varchar(255), primary key (id))
create CACHED table Customer (username varchar(255) not null, email varchar(255), first varchar(255), last varchar(255), password varchar(255), primary key (username))
create CACHED table Customer_Booking (Customer_username varchar(255) not null, bookings_id bigint not null, primary key (Customer_username, bookings_id), unique (bookings_id))
create CACHED table Hotel (id bigint generated by default as identity (start with 1), address varchar(255), city varchar(255), country varchar(255), name varchar(255), price numeric(6,2), state varchar(255), zip varchar(255), primary key (id))
create CACHED table Hotel_Booking (Hotel_id bigint not null, bookings_id bigint not null, primary key (Hotel_id, bookings_id), unique (bookings_id))
alter table Booking add constraint FK6713A039BF91BB8D foreign key (hotel_id) references Hotel
alter table Booking add constraint FK6713A03975CC21E2 foreign key (user_username) references Customer
alter table Customer_Booking add constraint FKBAF24CF8C283C22C foreign key (bookings_id) references Booking
alter table Customer_Booking add constraint FKBAF24CF8AFFB732F foreign key (Customer_username) references Customer
alter table Hotel_Booking add constraint FKC3FD448EC283C22C foreign key (bookings_id) references Booking
alter table Hotel_Booking add constraint FKC3FD448EBF91BB8D foreign key (Hotel_id) references Hotel
create CACHED table hibernate_sequences ( sequence_name varchar(255),  sequence_next_hi_value integer )